config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'page#lp'
  get 'service', to: 'page#index'
  get 'products', to: 'page#products'
  get 'company', to: 'page#company'
  get 'recruit', to: 'page#recruit'
  get 'contact', to: 'page#contact'
  get 'error', to: 'page#error'
  get 'service/media_consulting', to: 'page#media_consulting'
  get 'service/human_resource_development', to: 'page#project_pr'
  get 'service/translation', to: 'page#translation'
  post 'inquiry', to: 'page#inquiry'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def top
  end

  def index
  end

  def products
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  protect_from_forgery :except => [:inquiry]

    def top
    end

    def lp
      @news= News.all
    end

    def contact
      @contact = Contact.new
    end

    def inquiry
      inquiry = Inquiry.new(
          company: params[:company],
          name: params[:name],
          tel: params[:tel],
          mail: params[:mail],
          confirmation_mail: params[:confirmation_mail],
          subject: params[:subject],
          message: params[:message]
      )
      if verify_recaptcha
        InquiryMailer.send_mail(inquiry).deliver_now
        redirect_to :action => 'contact'
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/page/_footer.html.haml
%footer
  %section.inner
    .l-footer__body
      .l-footer__body__logo
        = image_tag 'logo_wh.png', alt: 'techtec'
      .l-footer__body__link
        %ul
          %li.l-footer__title
            ABOUT
          %li.l-footer__link
            =link_to "ホーム", '/', class: "l-footer__content"
          %li.l-footer__link
            =link_to "サービス一覧", service_path, class: "l-footer__content"
          %li.l-footer__link
            =link_to "プロダクト一覧", products_path, class: "l-footer__content"
          %li.l-footer__link
            =link_to "会社情報", company_path, class: "l-footer__content"
          %li.l-footer__link
            =link_to "採用情報", recruit_path, class: "l-footer__content"
          %li.l-footer__link
            =link_to "お問い合わせ", contact_path, class: "l-footer__content"
        %ul
          %li.l-footer__title
            SERVICE
          %li.l-footer__link
            =link_to "メディアサポート事業", '/service/media_consulting', class: "l-footer__content"
          %li.l-footer__link
            =link_to "人材育成事業", '/service/human_resource_development', class: "l-footer__content"
          %li.l-footer__link
            =link_to "翻訳・採用事業", '/service/translation', class: "l-footer__content"
        %ul
          %li.l-footer__title
            PRODUCT
          %li.l-footer__link
            =link_to "PoL(ポル)", "https://pol.techtec.world", class: "l-footer__content", target: [:_blank]
          %li.l-footer__link
            =link_to "techtec", "https://techtec.site", class: "l-footer__content", target: [:_blank]
          %li.l-footer__link
            =link_to "Hi Blockchain", "https://hi-blockchain.world/", class: "l-footer__content", target: [:_blank]
        %ul
          %li.l-footer__title
            COMMUNITY
          %li.l-footer__link
            =link_to "Twitter", "https://twitter.com/PoL_techtec", class: "l-footer__content", target: [:_blank]
          %li.l-footer__link
            =link_to "Facebook", "https://www.facebook.com/PoLtechtec/", class: "l-footer__content", target: [:_blank]
          %li.l-footer__link
            =link_to "connpass", "https://techtec.connpass.com/", class: "l-footer__content", target: [:_blank]
          %li.l-footer__link
            =link_to "会社ブログ", "https://medium.com/techtec", class: "l-footer__content", target: [:_blank]
    .l-footer__copyright
      %p ​©︎2019 • techtec Inc.

app/views/page/_header.html.haml
%header.l-header{ role: 'banner' }
  .l-header__body
    %div.l-header__logo
      = link_to image_tag('logo.png', alt: 'techtecコーポレート'), '/'

    %div.l-header__logo-sp
      = link_to image_tag('logo.png', alt: 'techtecコーポレート'), '/'

    .l-header__nav-toggle
      = image_tag 'ic_toggle.png'

    %ul.l-header__list
      %li.l-header__link
        = link_to "HOME", '/', class: "l-header__content"
      %li.l-header__link
        = link_to "SERVICE", service_path, class: "l-header__content"
      %li.l-header__link
        = link_to "PRODUCT", products_path, class: "l-header__content"
      %li.l-header__link
        = link_to "COMPANY", company_path, class: "l-header__content"
      %li.l-header__link
        = link_to "NEWS", "https://hi-blockchain.world/category/pol-news", class: "l-header__content l-header__content_blank", target: [:_blank]
      %li.l-header__link
        = link_to "COMMUNITY", "https://techtec.connpass.com/", class: "l-header__content l-header__content_blank", target: [:_blank]
      %li.l-header__link
        = link_to "CONTACT", contact_path, class: "l-header__content"
      %li.l-header__link.l-header__btn
        = link_to "RECRUIT", recruit_path, class: "l-top-header__content"

.l-header__nav-sp
  %nav
    %ul
      %li.l-header__link
        = link_to "HOME", '/', class: "l-header__content"
      %li.l-header__link
        = link_to "SERVICE", service_path, class: "l-header__content"
      %li.l-header__link
        = link_to "PRODUCT", products_path, class: "l-header__content"
      %li.l-header__link
        = link_to "COMPANY", company_path, class: "l-header__content"
      %li.l-header__link
        = link_to "NEWS", "https://hi-blockchain.world/category/pol-news", class: "l-header__content l-header__content_blank", target: [:_blank]
      %li.l-header__link
        = link_to "COMMUNITY", "https://techtec.connpass.com/", class: "l-header__content l-header__content_blank", target: [:_blank]
      %li.l-header__link
        = link_to "RECRUIT", recruit_path, class: "l-header__content"
      %li.l-header__link
        = link_to "CONTACT", contact_path, class: "l-header__content"

%script{:crossorigin => "anonymous", :integrity => "sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=", :src => "https://code.jquery.com/jquery-3.1.1.min.js"}
:javascript
  $(function() {
    $('.l-header__nav-toggle').click(function(){
      if ($(this).hasClass('open')) {
        $('.l-header__nav-sp').fadeOut();
        $('body').removeClass('fixed');
        $(this).find('img').attr('src','/assets/ic_toggle.png');
        $(this).removeClass('open');
      } else {
        $('.l-header__nav-sp').fadeIn();
        $('body').addClass('fixed');
        $(this).find('img').attr('src','/assets/ic_close.png');
        $(this).addClass('open');
      }
    })
  })

app/views/page/_top_header.html.haml
%header.l-header.l-top-header{ role: 'banner' }
  .l-header__body
    %div.l-header__logo
      = link_to image_tag('logo_white.png', alt: 'techtecコーポレート'), '/'

    %div.l-header__logo-sp
      = link_to image_tag('logo.png', alt: 'techtecコーポレート'), '/'

    .l-header__nav-toggle
      = image_tag 'ic_toggle.png'

    %ul.l-header__list
      %li.l-header__link
        = link_to "HOME", '/', class: "l-top-header__content"
      %li.l-header__link
        = link_to "SERVICE", service_path, class: "l-top-header__content"
      %li.l-header__link
        = link_to "PRODUCT", products_path, class: "l-top-header__content"
      %li.l-header__link
        = link_to "COMPANY", company_path, class: "l-top-header__content"
      %li.l-header__link
      = link_to "NEWS", "https://hi-blockchain.world/category/pol-news", class: "l-top-header__content l-top-header__content_blank", target: [:_blank]
      %li.l-header__link
        = link_to "COMMUNITY", "https://techtec.connpass.com/", class: "l-top-header__content l-top-header__content_blank", target: [:_blank]
      %li.l-header__link
        = link_to "CONTACT", contact_path, class: "l-top-header__content"
      %li.l-header__link.l-header__btn.l-top-header__btn
        = link_to "RECRUIT", recruit_path, class: "l-top-header__content"

.l-header__nav-sp
  %nav
    %ul
      %li.l-header__link
        = link_to "HOME", '/', class: "l-header__content"
      %li.l-header__link
        = link_to "SERVICE", service_path, class: "l-header__content"
      %li.l-header__link
        = link_to "PRODUCT", products_path, class: "l-header__content"
      %li.l-header__link
        = link_to "COMPANY", company_path, class: "l-header__content"
      %li.l-header__link
        = link_to "NEWS", "https://hi-blockchain.world/category/pol-news", class: "l-header__content l-header__content_blank", target: [:_blank]
      %li.l-header__link
        = link_to "COMMUNITY", "https://techtec.connpass.com/", class: "l-header__content l-header__content_blank", target: [:_blank]
      %li.l-header__link
        = link_to "RECRUIT", recruit_path, class: "l-header__content"
      %li.l-header__link
        = link_to "CONTACT", contact_path, class: "l-header__content"

%script{:crossorigin => "anonymous", :integrity => "sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=", :src => "https://code.jquery.com/jquery-3.1.1.min.js"}
:javascript
  $(function() {
    $('.l-header__nav-toggle').click(function(){
      if ($(this).hasClass('open')) {
        $('.l-header__nav-sp').fadeOut();
        $('body').removeClass('fixed');
        $(this).find('img').attr('src','/assets/ic_toggle.png');
        $(this).removeClass('open');
      } else {
        $('.l-header__nav-sp').fadeIn();
        $('body').addClass('fixed');
        $(this).find('img').attr('src','/assets/ic_close.png');
        $(this).addClass('open');
      }
    })
  })

app/views/page/contact.html.haml


!!!
%html
  = stylesheet_link_tag 'application', media: 'all'
  = javascript_include_tag 'application'
  %head
    %title CONTACT - 株式会社techtec
    %meta{ name: 'description', content: '株式会社techtecに関するお問い合わせや採用、その他パートナーシップや取材に関するご相談は、随時お気軽にお寄せください。'}
    %meta{ content: 'text/html; charset=UTF-8', http: { equiv: 'Content-Type' } }
    %meta{ content: 'width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes', name: 'viewport' }
    = favicon_link_tag 'favicon', rel: 'icon', href: '/assets/favicon.ico'
  %body
  = render 'header'
  .c-body
    .c-contact
      %section
        .c-body__title.c-contact__title
          %h2.c-body__heading CONTACT
          %span.c-body__subhead 一緒にできること
        %p.c-contact__text 株式会社techtecに関するお問い合わせや採用、</br>その他パートナーシップや取材に関するご相談は以下よりお願いいたします。
        .c-contact__form
          %form{action: '/inquiry', method: 'post'}
            .c-contact__item
              %p.c-contact__label
                会社名
                %span.c-contact__must *
              .c-contact__input
                %input{name: 'company', id:'company'}
            .c-contact__item
              %p.c-contact__label
                氏名
                %span.c-contact__must *
              .c-contact__input
                %input{name: 'name', id:'name'}
            .c-contact__item
              %p.c-contact__label
                電話番号
                %span.c-contact__must *
              .c-contact__input
                %input{name: 'tel', id:'tel'}
            .c-contact__item
              %p.c-contact__label
                メールアドレス
                %span.c-contact__must *
              .c-contact__input
                %input{name: 'mail', id:'mail', class:'long'}
            .c-contact__item
              %p.c-contact__label
                メールアドレス確認
                %span.c-contact__must *
              .c-contact__input
                %input{name: 'confirmation_mail', id:'confirmation_mail', class:'long'}
            .c-contact__item
              %p.c-contact__label
                件名
                %span.c-contact__must *
              .c-contact__input
                %input{name: 'subject', id:'subject', class:'long'}
            .c-contact__item
              %p.c-contact__label
                本文
                %span.c-contact__must *
              .c-contact__input
                %textarea{rows: 6, name: 'message', id:'message', class:'long'}
            .c-contant__button
              .c-contact__button__robot
                =recaptcha_tags callback: 'recaptcha'
              .c-contact__button__submit
                %input{value: '送信', class: 'c-form__submit', id: 'confirmation_button', type: 'button', onclick: 'confirm_inquiry_mail();', disabled: true}
                %input{type: 'submit', id:'submit', style:'display: none'}

  = render 'footer'

app/views/page/error.html.haml
!!!
%html
  = stylesheet_link_tag 'application', media: 'all'
  %head
    %meta{ content: 'text/html; charset=UTF-8', http: { equiv: 'Content-Type' } }
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
    = favicon_link_tag 'favicon', rel: 'icon', href: '/assets/favicon.ico'
  %body
  = render 'header'
  .c-body
    .e-body
      %section.inner
        %h2.e-body__title Is this Orphanblock...?
        %p.e-body__desc 該当するページが存在しません
        .e-body__image
          = image_tag 'img_error.png'
          
  = render 'footer'